language: node_js
node_js:
 - "0.11"
 - "0.10"
before_script:
 # install dependencies
 - gem update --system
 - gem install compass --pre
 - gem install susy sass-globbing
 - npm install -g grunt-cli bower
script:
 # We want to gate on passing tests and a successful build
 - bower install
 - grunt
