language: node_js
node_js:
 - "0.11"
 - "0.10"
 - "0.8"
before_script:
 # install dependencies
 - gem update --system
 - gem install compass
 - gem install susy
 - gem install sass-globbing
 - npm install -g grunt-cli bower
script:
 # We want to gate on passing tests and a successful build
 - bower install
 - grunt
